### ISSUE TITLE
Add a new rule to blacklist rules

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AGLint#214]
There have been cases a problematic rule was removed and then readded, causing the trouble again. A recent example is https://github.com/AdguardTeam/AdguardFilters/commit/dea5d96863cf30ad6f109ec60b55a598403b25aa but there were many more. I knew the rule would be readded, hence left a [comment](https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/specific.txt#L51) but it didn't prevent. While other repos such as EL also suffer this sort of issue, it tends to happen on AG more as the number of people working is the largest with some members not being aware of removel of the problematic rule. Adding a blacklist to check before commit will mitigate the problem, e.g. register `staff-start.com/js/track/` and any rule including `staff-start.com/js/track/` will be warned.

**Comment by Yuki2718** [comment]
FWIW a similar case in EL:
`||static.lefigaro.fr/figconsent/` was removed for https://github.com/easylist/easylist/issues/16487 and then readded by https://github.com/easylist/easylist/pull/18154 , caused https://github.com/uBlockOrigin/uAssets/discussions/25030#discussioncomment-10439394

**Comment by scripthunter7** [comment]
There are two options here, one is to accept the regexps and blacklist all rules that match these regexps, and blacklist the exact rule texts

**Comment by scripthunter7** [comment]
@Yuki2718 i mean, we can add both)

We can specify the config like this (`.aglintrc.yaml`)

```yaml
root: true
extends:
  - aglint:recommended
syntax:
  - AdGuard
rules:
  no-excluded-rules:
    # exclude all rules that match at least one pattern from here
    exclude-patterns:
      - /regex/
    # exclude all rules listed here (character correct match)
    exclude-rules:
      - '||example.com/donotblock.css'
      - '/donotblock.js'
```
